alias r := runserver
alias run := runserver
alias m := migrate
alias mm := makemigrations


test:
  pytest {{cookiecutter.project_slug}}

runserver:
  python manage.py runserver localhost:8000

migrate:
  python manage.py migrate

{% raw -%}
makemigrations +ARGS:
  python manage.py makemigrations {{ARGS}}
{%- endraw %}

ruff:
  ruff check {{cookiecutter.project_slug}}
